name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Primeiro Job"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Primeira Ação"
        run: echo "Teste MSG"
      - name: "Segunda Ação"
        run: |
          echo "Primeiro Worlow criado"
          echo "Success"
      - name: "Script Python"
        run: |
          variavel = "Msg Python"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalação do ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps: 
       - name: "Veriicação do node js arual"
         run: node --version
       - name: "Definir versão node js"
         uses: actions/setup-node@v4
         with:
          node-version: '20.13.1'
       - name: "Verificação após instalação"
         run: node --version
