name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Primeiro Job"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Primeira Ação"
        run: echo "Teste MSG"
      - name: "Segunda Ação"
        run: |
          echo "Primeiro Worlow criado"
          echo "Success"
      
